### ISSUE TITLE
现在每次滑动返回上一个Activity后，都是再次刷新布局，导致整个页面看起来重新加载了遍

### ISSUE THREAD

**Issue by PoetGcc** [xwc520/BusinessComponent#10]

**Comment by YxmCute** [comment]
建议留下机型和相应的刷新视频录屏

1.  排出上一个activity中是否执行了onactivityresult或者是onresume等刷新方法
2. 是否用了沉浸式状态栏的框架等等

**Comment by XWC95** [comment]
滑动到上一个界面本身就会重绘的，这是 Android 的机制，和按back键一样。但我这里确实多重绘了一次，现已修复。感谢您的反馈

**Comment by XWC95** [comment]
您可以使用最新版本
