### ISSUE TITLE
侧滑返回库在刘海屏手机的问题

### ISSUE THREAD

**Issue by liweiGe** [xwc520/BusinessComponent#11]
在没有刘海的手机运行良好,但是在有刘海的手机上会有适配问题,问题在底部有输入框的情况下输入框下面会有一小块留白,差不多是状态栏的高度,
 android:windowSoftInputMode="adjustResize"  设置这个属性之后才有这个情况
![image](https://user-images.githubusercontent.com/25901728/65735908-ad4e7200-e10b-11e9-9e55-214cc673b1d9.png)

**Comment by xwc520** [comment]
什么型号的手机，我怎么感觉和侧滑库没有关系啊

**Comment by XWC95** [comment]
什么型号的手机

**Comment by XWC95** [comment]
会不会是你的布局设置了底部边距。

**Comment by liweiGe** [comment]
> 会不会是你的布局设置了底部边距。

没有设置底部边距啊,小米8,凡是刘海屏的手机都能复现
activity里有个输入框,并且设置android:windowSoftInputMode="adjustResize"

**Comment by XWC95** [comment]
我特意拿了一台小米8，试了一下。没有发现相同问题。

**Comment by XWC95** [comment]
你试下不初始化这个库。看看有没有相同问题吧
