### ISSUE TITLE
在申请权限的Activity发生崩溃

### ISSUE THREAD

**Issue by YxmCute** [xwc520/BusinessComponent#8]
java.lang.IllegalStateException: Width must have an exact value or MATCH_PARENT

**Comment by YxmCute** [comment]
在Activity的setContentView()后执行的请求权限操作
然后测试了   去掉侧滑库后就没问题
权限库是AndPermission

**Comment by XWC95** [comment]
修复好了，请更新一下依赖库版本

**Comment by XWC95** [comment]
感谢您的反馈

**Comment by YxmCute** [comment]
> 感谢您的反馈

劳烦讲解之前抛出异常的逻辑，有点不太懂。
